### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by Piiiipa** [bedrock-tool/bedrocktool#184] opened 2024-06-16 06:54 UTC
how can i fix Error: POST https://login.live.com/oauth20_connect.srf: Post "https://login.live.com/oauth20_connect.srf": dial tcp: lookup login.live.com: i/o timeout?

**Comment by olebeck** [comment] 2024-07-12 15:22
found the cause of this issue, should be fixed now

**Closed by olebeck** 2024-07-12 15:22 UTC
Labels: bug
