### ISSUE TITLE
-preload=false flag crashes 

### ISSUE THREAD

**Issue by jqms** [bedrock-tool/bedrocktool#11] opened 2022-12-10 19:23 UTC
```-preload=false skins-proxy``` crashes it without warning

**Comment by olebeck** [comment] 2022-12-15 19:09
closing the issue for now since i cant reproduce the error, feel free to reopen if you still have the issue and can help with reproducing the error so it can be fixed!

**Closed by olebeck** 2022-12-15 19:09 UTC

**Comment by jqms** [comment] 2022-12-19 22:55
it crashes immediately after pressing enter when adding the flag
eg
-preload=false worlds

**Comment by olebeck** [comment] 2022-12-20 15:03
how exactly are you running the program

**Comment by jqms** [comment] 2022-12-21 23:16
> 

double clicking it and opening it

**Comment by olebeck** [comment] 2022-12-22 23:05
To use extra cli flags you need to run it through a console, the interactive input only supports selecting the subcommand

**Comment by olebeck** [comment] 2022-12-24 13:04
this should now work with the new usability change

**Comment by jqms** [comment] 2022-12-24 14:40
alright neat
