### ISSUE TITLE
Can't load world on other server software

### ISSUE THREAD

**Issue by ZEENPOSTER** [bedrock-tool/bedrocktool#29] opened 2023-01-21 11:17 UTC
**Describe the bug**
when you try to use world on server software like dragonfly pocketmine(pm5) and nukkit 2.0 the server can't read biome data  

**Expected behavior**
can load on server with out any problem

**Screenshots**
![image](https://user-images.githubusercontent.com/87850291/213864313-d38fd96b-57cf-4d78-9456-2d4980ffcfad.png)
![image](https://user-images.githubusercontent.com/87850291/213864494-5d82304b-0300-4402-b0d9-c925b35cff4a.png)

**Additional context**
these server software can load normal bedrock world without any problem

**Comment by olebeck** [comment] 2023-01-21 13:26
Can you say what server this is on so I can do more testing

**Comment by ZEENPOSTER** [comment] 2023-01-21 14:04
hmm i mean i can't load map that i use world downloader in my server 
(i use this tool to download map form hive and i can't use it with my server )

**Comment by olebeck** [comment] 2023-01-21 19:01
does it load in the minecraft client

**Comment by ZEENPOSTER** [comment] 2023-01-22 01:45
yea it can load on minecraft client without any problem

**Comment by olebeck** [comment] 2023-01-22 01:57
fairly sure i know what the issue is then.
the world version hive uses is still 1.17 which uses 0-255 biomes while the current version expects -64-319 blocks
the minecraft client can handle it just fine but servers expect worlds to be in the current version.
to fix it you can use https://chunker.app/ to upgrade the world to current version, closing the issue if you still have problems feel free to reopen

**Closed by olebeck** 2023-01-22 01:57 UTC
Labels: bug
