### ISSUE TITLE
Cant download worlds from servers

### ISSUE THREAD

**Issue by xGAMEZAx** [bedrock-tool/bedrocktool#14] opened 2022-12-16 19:16 UTC
Also sometimes when i try to download worlds from server it only say: 

Enter Server: geo.hivebedrock.network
time="2022-12-16T13:12:06-06:00" level=info msg="Listening on [::]:19132"

![Captura de pantalla (10)](https://user-images.githubusercontent.com/120748737/208172130-1dfdee3c-8684-4839-b169-d8890526bda4.png)

**Comment by olebeck** [comment] 2022-12-17 03:40
the issue is that there is already another program or instance of bedrocktool listening for on port 19132, close that and then it should work

**Comment by xGAMEZAx** [comment] 2022-12-17 10:31
> the issue is that there is already another program or instance of bedrocktool listening for on port 19132, close that and then it should work

yea the one that is in the screenshot, and what about this
![Captura de pantalla (11)](https://user-images.githubusercontent.com/120748737/208237575-a1008f48-2a75-4ada-b246-a22c7cccbe90.png)

**Comment by xGAMEZAx** [comment] 2022-12-17 10:38
thanks

**Comment by olebeck** [comment] 2022-12-17 17:28
if its fixed you can close the issue.

**Closed** 2022-12-24 08:42 UTC
