### ISSUE TITLE
World saved from tool fails to get imported into Minecraft

### ISSUE THREAD

**Issue by mb824** [bedrock-tool/bedrocktool#118] opened 2023-10-22 06:11 UTC
The .mcworld file doesn't get imported into Minecraft. I only tried with the Hive Hub.

1. Download the Hive Hub using the tool.
2. Try to import the world saved by the tool.
3. Minecraft says, "World import failed".

The world should get imported into Minecraft

 - OS: Windows 11
 - Version 1.32.0-30
 - Minecraft Version 1.20.32

**Comment by olebeck** [comment] 2023-10-24 16:48
can you show the folder names in the resourcepacks folder in the mcworld file (you can open it with 7zip or any other program that can open zips)

**Comment by mb824** [comment] 2023-10-24 16:54
Sure, here you go.
![image](https://github.com/bedrock-tool/bedrocktool/assets/56483324/1ac21b7f-3406-4302-8c6a-b780526ea194)

**Comment by olebeck** [comment] 2023-10-25 14:05
the issue is in CTF Assets_5b66445d-a203-3fa1-ac97-a01f5b563711 as a temporary fix you can remove that resource pack

**Comment by mb824** [comment] 2023-10-25 15:01
This seems to have fixed it. Thanks!

**Comment by olebeck** [comment] 2024-07-12 15:26
fixed by not putting uuid in the name automatically

**Closed by olebeck** 2024-07-12 15:26 UTC
Labels: bug
